spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
      #defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} - for local
  instance:
    preferIpAddress: true