version: "3"
services:
  commmon-service:
    container_name: commmon-service
    build:
      context: ../business-services/common/target/
      args:
        - JAR_NAME_TO_RUN=common-0.0.1-SNAPSHOT-spring-boot.jar
        - LABEL_GROUP=configuration-server
        - LABEL_ID=config
        - LABEL_DESCRIPTION=this is configuration server
        - PORT_TO_EXPOSE=8085
    image: config-server:latest
    ports:
      - "8085:8085"

  api:
    container_name: api
    build:
      context: ../platform-services/apigateway/api/target
      args:
        - JAR_NAME_TO_RUN=api-0.0.1-SNAPSHOT-spring-boot.jar
        - LABEL_GROUP=proxy
        - LABEL_ID=zuul
        - LABEL_DESCRIPTION=this application uses zuul proxy
        - PORT_TO_EXPOSE=8081
    image: api:latest
    ports:
      - "8081:8081"

  ui-application:
    container_name: ui-zuul
    build:
      context: ../platform-services/apigateway/ui-application/target
      args:
        - JAR_NAME_TO_RUN=ui-application-0.0.1-SNAPSHOT-spring-boot.jar
        - LABEL_GROUP=proxy
        - LABEL_ID=ui-zool
        - LABEL_DESCRIPTION=ui for with using zuul proxy
        - PORT_TO_EXPOSE=8080
    image: ui:latest
    ports:
      - "8080:8080"

  eureka-server:
    container_name: eureka-server
    build:
      context: ../platform-services/discovery/eureka-server/target
      args:
        - JAR_NAME_TO_RUN=eureka-server-0.0.1-SNAPSHOT-spring-boot.jar
        - LABEL_GROUP=server
        - LABEL_ID=eureka
        - LABEL_DESCRIPTION=eureka server
        - PORT_TO_EXPOSE=8080
    image: eureka-server:latest
    ports:
      - "8761:8761"

  eureka-client:
    container_name: eureka-client
    build:
      context: ../platform-services/discovery/eureka-client/target
      args:
        - JAR_NAME_TO_RUN=eureka-client-0.0.1-SNAPSHOT-spring-boot.jar
        - LABEL_GROUP=client
        - LABEL_ID=eureka
        - LABEL_DESCRIPTION=eureka client
        - PORT_TO_EXPOSE=8090
    image: eureka-client:latest
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server

  feign-client:
    container_name: feign-client
    build:
      context: ../platform-services/discovery/feign-client/target
      args:
        - JAR_NAME_TO_RUN=feign-client-0.0.1-SNAPSHOT-spring-boot.jar
        - LABEL_GROUP=client
        - LABEL_ID=eureka
        - LABEL_DESCRIPTION=eureka client
        - PORT_TO_EXPOSE=8090
    image: feign-client:latest
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server